# .github/workflows/unzip.yml

name: Unzip and Commit Website

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  unzip_and_commit:
    runs-on: ubuntu-latest

    # 授予工作流写入仓库的权限
    permissions:
      contents: write

    steps:
      # 1. 检出仓库代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 解压文件到根目录
      - name: Unzip archive
        run: unzip -o weic-website.zip

      # 3. 提交并推送解压后的文件
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          if ! git diff-index --quiet HEAD; then
            git commit -m "Automated: Unzip website files"
            git push
          else
            echo "No changes to commit."
          fi
