# .github/workflows/unzip.yml

name: Unzip and Commit Website

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  unzip_and_commit:
    runs-on: ubuntu-latest

    # --- 添加下面这部分来授予写入权限 ---
    permissions:
      contents: write
    # ------------------------------------

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Unzip archive
        run: unzip -o weic-website.zip

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          if ! git diff-index --quiet HEAD; then
            git commit -m "Automated: Unzip website files"
            git push
          else
            echo "No changes to commit."
          fi
