name: Unzip WEIC Website

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # 添加手动触发支持

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Unzip weic-website.zip
        run: |
          unzip weic-website.zip -d ./
        working-directory: ${{ github.workspace }}

      - name: List Files
        run: ls -la
        working-directory: ${{ github.workspace }}
