name: Test Unzip

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Check if zip exists
        run: |
          ls -la
          if [ -f "weic-website.zip" ]; then
            echo "Zip file found!"
            unzip weic-website.zip -d ./
          else
            echo "Error: weic-website.zip not found!"
            exit 1
          fi
      - name: List Files
        run: ls -la
