name: Test Unzip

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check if zip exists
        run: |
          ls -la
          if [ -f "weic-website.zip" ]; then
            echo "Zip file found!"
          else
            echo "Error: weic-website.zip not found!"
            exit 1
          fi

      - name: Verify Zip File
        run: |
          unzip -l weic-website.zip  # 列出 zip 文件内容
        working-directory: ${{ github.workspace }}

      - name: Unzip weic-website.zip
        run: |
          unzip -o weic-website.zip -d ./  # -o 强制覆盖
          echo "Unzip completed. Listing files:"
          ls -laR  # 递归列出所有文件
        working-directory: ${{ github.workspace }}

      - name: Commit Unzipped Files
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Unzip weic-website.zip" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: List Files After Commit
        run: ls -laR
        working-directory: ${{ github.workspace }}
