name: Unzip File

on:
  workflow_dispatch: # 手动触发工作流
    inputs:
      zip_file: # 压缩文件路径
        description: 'Path to the zip file (e.g., folder/archive.zip)'
        required: true
      destination: # 解压目标路径
        description: 'Destination folder for unzipped files (e.g., folder/unzipped)'
        required: true

jobs:
  unzip-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Unzip file
        run: |
          unzip -o ${{ github.event.inputs.zip_file }} -d ${{ github.event.inputs.destination }}
        shell: bash

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add .
          git commit -m "Unzip ${{ github.event.inputs.zip_file }} to ${{ github.event.inputs.destination }}"
          git push
        shell: bash
